name: flutter_distributor
description: A complete tool for packaging and publishing your Flutter apps.
version: 0.4.5
homepage: https://distributor.leanflutter.dev
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_distributor
issue_tracker: https://github.com/leanflutter/flutter_distributor/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.2.0
  charset: ^2.0.1
  dio: ^5.3.4
  flutter_app_builder: ^0.4.5
  flutter_app_packager: 
    path: ../flutter_app_packager
  flutter_app_publisher: ^0.4.5
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.1.0
  shell_executor: ^0.1.6
  shell_uikit: ^0.1.1
  yaml: ^3.1.0

# dart pub outdated
# Remove-Item -Path ".dart_tool" -Recurse;dart pub global activate --source path .
dependency_overrides:
  # image: ^4.5.2
  # archive: ^4.0.2
  # petitparser: ^6.1.0
  # http: ^1.3.0
  # get_it: ^8.0.3
  # qiniu_sdk_base: ^0.7.0
  # uuid: ^4.5.1
  # lints: ^5.1.1
  # web_socket_channel: ^3.0.2
  # glob: ^2.1.3
  # dio: ^5.8.0+1
  # dio_web_adapter: ^2.1.0
  # async: ^2.13.0
  dependency_validator: ^5.0.2
  test: ^1.25.15
  _fe_analyzer_shared: ^80.0.0
  analyzer: ^7.3.0
  shelf_web_socket: ^3.0.0
  dio_web_adapter: ^2.1.1

dev_dependencies:
  dependency_validator: ^3.0.0
  mostly_reasonable_lints: ^0.1.2
  test: ^1.23.1

executables:
  flutter_distributor: main
